SELECT T.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO as I
JOIN ITEM_TREE as T
ON I.ITEM_ID = T.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC